# see docs at https://github.com/realm/SwiftLint

disabled_rules:
  - function_parameter_count
  - trailing_newline
  - closure_parameter_position
  - opening_brace
  - nesting
  - function_body_length
  - file_length

# rules options:

line_length:
  ignores_comments: true
trailing_whitespace:
  ignores_empty_lines: true
type_name:
  allowed_symbols: _
statement_position:
  # https://github.com/realm/SwiftLint/issues/1181#issuecomment-272445593
  statement_mode: uncuddled_else