git:
  depth: 3
  submodules: false

language: objective-c

osx_image:
  - xcode10.2

before_install:
 - bundle install --path .vendor/bundle --jobs=3 --retry=3 --deployment
 - bundle exec pod repo update

install:
 - bundle exec pod install

before_script:
  # cd ./.setup && swift run && cd ./.. # RUN this manually!
  - bundle exec fastlane generateProjectViaSwiftPM

xcode_project: XCERepoConfigurator.xcodeproj
xcode_scheme: XCERepoConfigurator-Package
xcode_destination: platform=macOS
