import FileKit

import XCERepoConfigurator

// MARK: - PRE-script invocation output

print("\n")
print("--- BEGIN of '\(Executable.name!)' script ---")

// MARK: -

// MARK: Parameters

 Spec.BuildSettings.swiftVersion.value = "4.2"

let localRepo = try Spec.LocalRepo.current()

let remoteRepo = try Spec.RemoteRepo()

let company = try Spec.Company(
    prefix: "XCE",
    identifier: "com.\(remoteRepo.accountName)"
)

let project = try Spec.Project(
    summary: "Repo description",
    copyrightYear: 2019,
    deploymentTargets: [
        .iOS : "9.0",
        .watchOS : "3.0",
        .tvOS : "9.0",
        .macOS : "10.11"
    ]
)

let license: CocoaPods.Podspec.License = (
    License.MIT.licenseType,
    License.MIT.relativeLocation
)

var cocoaPod = try Spec.CocoaPod(
    companyInfo: .from(company),
    productInfo: .from(project),
    authors: [
        ("Maxim Khatskevich", "maxim@khatskevi.ch")
    ]
)

try? cocoaPod.readCurrentVersion(
    callFastlane: .viaBundler
)

let subSpecs = (
    core: Spec.CocoaPod.SubSpec("Core"),
    operators: Spec.CocoaPod.SubSpec("Operators"),
    tests: Spec.CocoaPod.SubSpec.tests()
)

// MARK: Parameters - Summary

localRepo.report()
remoteRepo.report()
company.report()
project.report()

// MARK: -

// MARK: Write - Dummy files

try [
    subSpecs.core,
    subSpecs.operators,
    subSpecs.tests
    ]
    .map{
        
        localRepo.location + $0.sourcesLocation
    }
    .map{
        
        try DummyFile().prepare(absolutePrefixLocation: $0)
    }
    .forEach{
        
        try $0.writeToFileSystem(ifFileExists: .skip)
    }

// MARK: Write - Bundler - Gemfile

// https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
try Bundler
    .Gemfile(
        basicFastlane: true,
        """
        gem 'cocoapods', '~> 1.6.0.beta.2'
        gem 'cocoapods-generate'
        """
    )
    .prepare()
    .writeToFileSystem()

// MARK: Write - ReadMe

try ReadMe()
    .addGitHubLicenseBadge(
        account: company.name,
        repo: project.name
    )
    .addGitHubTagBadge(
        account: company.name,
        repo: project.name
    )
    .addCocoaPodsVersionBadge(
        podName: cocoaPod.fullName
    )
    .addCocoaPodsPlatformsBadge(
        podName: cocoaPod.fullName
    )
    .addSwiftPMCompatibleBadge()
    .addCarthageCompatibleBadge()
    .addWrittenInSwiftBadge(
        version: Spec.BuildSettings.swiftVersion.value
    )
    .add("""

        # MyFwk

        Project description goes here...

        """
    )
    .prepare(
        removeRepeatingEmptyLines: false
    )
    .writeToFileSystem()

// MARK: Write - SwiftLint

try SwiftLint
    .standard()
    .prepare()
    .writeToFileSystem()

// MARK: Write - License

try License
    .MIT(
        copyrightYear: project.copyrightYear,
        copyrightEntity: cocoaPod.authors[0].name
    )
    .prepare()
    .writeToFileSystem()

// MARK: Write - CocoaPods - Podspec

try CocoaPods
    .Podspec
    .withSubSpecs(
        product: cocoaPod.product,
        company: cocoaPod.company,
        version: cocoaPod.currentVersion,
        license: license,
        authors: cocoaPod.authors,
        swiftVersion: Spec.BuildSettings.swiftVersion.value,
        perPlatformSettings: {
            
            globalContext in
            
            //declare support for all defined deployment targets
            
            project
                .deploymentTargets
                .forEach{ globalContext.settings(for: $0) }
        },
        subSpecs: {

            $0.subSpec(subSpecs.core.name){

                $0.settings(
                    .sourceFiles(subSpecs.core.sourcesPattern)
                )
            }

            $0.subSpec(subSpecs.operators.name){
                
                $0.settings(
                    .dependency("\(cocoaPod.fullName)/\(subSpecs.core.name)"),
                    .sourceFiles(subSpecs.operators.sourcesPattern)
                )
            }
        },
        testSubSpecs: {

            $0.testSubSpec(subSpecs.tests.name){

                $0.settings(
                    .noPrefix("requires_app_host = false"),
                    .dependency("SwiftLint"), // we will be running linting from unit tests!
                    .sourceFiles(subSpecs.tests.sourcesPattern)
                )
            }
        }
    )
    .prepare(for: cocoaPod)
    .writeToFileSystem()

// MARK: Write - Fastlane - Fastfile

try Fastlane
    .Fastfile
    .ForLibrary()
    .defaultHeader()
    .beforeRelease(
        podspecLocation: .from(cocoaPod)
    )
    .lane("lintThoroughly"){

        "pod_lib_lint"
    }
    .generateProjectViaCP(
        callCocoaPods: .viaBundler,
        prefixLocation: cocoaPod.xcodeArtifactsLocation,
        scriptBuildPhases: {

            // NOTE: we inject build phase script into 'Pods' project
            // auto-generated by 'cocoapods-generate' for our 'cocoaPod'
            
            try $0.swiftLint(
                project: cocoaPod.generatedXcodeProjectLocation,
                // NOTE: regardless of subspecs, targets are generated per platform
                targetNames: project
                    .deploymentTargets
                    .keys
                    .map{ "\(cocoaPod.fullName)-\($0.rawValue)" },
                params: [

                    // NOTE: the '${SRCROOT}' of 'Pods' points inside "./Xcode/MyFwk/"
                    
                    """
                    --path "${SRCROOT}/../../\(Spec.Locations.sources.rawValue)"
                    """
                ]
            )
        },
        endingEntries: [

            """
            # NOTE: Origin path MUST be absolute in order the symlink to work properly!
            sh 'cd ./.. && \(Utils.symLinkCmd(("$PWD" + SwiftLint.relativeLocation).rawValue, subSpecs.core.linterCfgLocation.rawValue))'
            sh 'cd ./.. && \(Utils.symLinkCmd(("$PWD" + SwiftLint.relativeLocation).rawValue, subSpecs.operators.linterCfgLocation.rawValue))'
            """
        ]
    )
    .generateProjectViaSwiftPM()
    .prepare()
    .writeToFileSystem()

// MARK: Write - GitHub - PagesConfig

try GitHub
    .PagesConfig()
    .prepare()
    .writeToFileSystem()

// MARK: Write - Git - .gitignore

try Git
    .RepoIgnore
    .framework(
        otherEntries: [
            """
            # we don't need to store any project files,
            # as we generate them on-demand from specs
            *.xcodeproj
            
            # folder for temporary development Xcode-related artifacts
            # generated by 'cocopods-generate'
            \(cocoaPod.xcodeArtifactsLocation.rawValue)
            
            # derived files generated by '.setup' script
            \(DummyFile.relativeLocation.rawValue)
            """
        ]
    )
    .prepare()
    .writeToFileSystem()

// MARK: Write - Package.swift

try CustomTextFile("""
    // swift-tools-version:\(Spec.BuildSettings.swiftVersion.value)

    import PackageDescription

    let package = Package(
        name: "\(cocoaPod.fullName)",
        products: [
            .library(
                name: "\(cocoaPod.fullName)",
                targets: [
                    "\(cocoaPod.fullName + subSpecs.core.name)"
                ]
            ),
            .library(
                name: "\(cocoaPod.fullName + "WithOperators")",
                targets: [
                    "\(cocoaPod.fullName + subSpecs.operators.name)"
                ]
            ),
        ],
        targets: [
            .target(
                name: "\(cocoaPod.fullName + subSpecs.core.name)",
                path: "\(subSpecs.core.sourcesLocation)"
            ),
            .target(
                name: "\(cocoaPod.fullName + subSpecs.operators.name)",
                dependencies: ["\(cocoaPod.fullName + subSpecs.core.name)"],
                path: "\(subSpecs.operators.sourcesLocation)"
            ),
            .testTarget(
                name: "\(cocoaPod.fullName + subSpecs.tests.name)",
                dependencies: [
                    "\(cocoaPod.fullName + subSpecs.core.name)",
                    "\(cocoaPod.fullName + subSpecs.operators.name)"
                ],
                path: "\(subSpecs.tests.sourcesLocation)"
            ),
        ],
        swiftLanguageVersions: [.v4, .v4_2]
    )
    """
    )
    .prepare(relativeLocation: ["Package.swift"])
    .writeToFileSystem()

// MARK: - POST-script invocation output

print("--- END of '\(Executable.name!)' script ---")
