# https://github.com/lyptt/struct/wiki/Spec-format:-v2.0

version: 2.1.0
configurations:
  debug:
    overrides:
      CURRENT_PROJECT_VERSION: '0'
      VERSIONING_SYSTEM: 'apple-generic'
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: 'YES'
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: 'YES'
      IPHONEOS_DEPLOYMENT_TARGET: '11.0'
      CLANG_WARN_COMMA: 'YES'
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: 'YES'
      CLANG_WARN_OBJC_LITERAL_CONVERSION: 'YES'
      CLANG_WARN_STRICT_PROTOTYPES: 'YES'
      DEVELOPMENT_TEAM: 'ABCXYZ123'
      SWIFT_VERSION: '4.2'
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: 'YES'
      SWIFT_OPTIMIZATION_LEVEL: '-Onone'
      CLANG_WARN_RANGE_LOOP_ANALYSIS: 'YES'
  release:
    overrides:
      CURRENT_PROJECT_VERSION: '0'
      VERSIONING_SYSTEM: 'apple-generic'
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: 'YES'
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: 'YES'
      IPHONEOS_DEPLOYMENT_TARGET: '11.0'
      CLANG_WARN_COMMA: 'YES'
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: 'YES'
      CLANG_WARN_OBJC_LITERAL_CONVERSION: 'YES'
      CLANG_WARN_STRICT_PROTOTYPES: 'YES'
      DEVELOPMENT_TEAM: 'ABCXYZ123'
      SWIFT_VERSION: '4.2'
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: 'YES'
      CLANG_WARN_RANGE_LOOP_ANALYSIS: 'YES'
targets:
  SimpleApp:
    platform: ios
    type: ":application"
    sources:
    - Sources/SimpleApp
    configurations:
      debug:
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        CLANG_WARN_COMMA: "YES"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        SWIFT_VERSION: "$(inherited)"
        DEBUG_INFORMATION_FORMAT: "dwarf"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        SDKROOT: "iphoneos"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        MTL_ENABLE_DEBUG_INFO: "YES"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        IPHONEOS_DEPLOYMENT_TARGET: "11.0"
        COPY_PHASE_STRIP: "NO"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        GCC_PREPROCESSOR_DEFINITIONS: "DEBUG1 $(inherited)"
        ONLY_ACTIVE_ARCH: "YES"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleApp"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        PRODUCT_NAME: "$(TARGET_NAME)"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_TESTABILITY: "YES"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        GCC_WARN_UNUSED_VARIABLE: "YES"
        MTL_FAST_MATH: "YES"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        GCC_DYNAMIC_NO_PIC: "NO"
        GCC_OPTIMIZATION_LEVEL: "0"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        INFOPLIST_FILE: "Info/SimpleApp.plist"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
      release:
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CODE_SIGN_IDENTITY: "iPhone Developer"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        SWIFT_COMPILATION_MODE: "wholemodule"
        CLANG_WARN_COMMA: "YES"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        SWIFT_VERSION: "$(inherited)"
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        SDKROOT: "iphoneos"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        ENABLE_NS_ASSERTIONS: "NO"
        MTL_ENABLE_DEBUG_INFO: "NO"
        VALIDATE_PRODUCT: "YES"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        IPHONEOS_DEPLOYMENT_TARGET: "11.0"
        COPY_PHASE_STRIP: "NO"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleApp"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        PRODUCT_NAME: "$(TARGET_NAME)"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        TARGETED_DEVICE_FAMILY: "1"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        GCC_WARN_UNUSED_VARIABLE: "YES"
        MTL_FAST_MATH: "YES"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        INFOPLIST_FILE: "Info/SimpleApp.plist"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
  SimpleAppTests:
    platform: ios
    type: ":bundle.unit-test"
    references:
    - location: SimpleApp
    sources:
    - Sources/SimpleAppTests
    configurations:
      debug:
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleAppTests"
        SWIFT_VERSION: "$(inherited)"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        MTL_ENABLE_DEBUG_INFO: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
        INFOPLIST_FILE: "Info/SimpleAppTests.plist"
        IPHONEOS_DEPLOYMENT_TARGET: "11.0"
      release:
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleAppTests"
        SWIFT_VERSION: "$(inherited)"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
        INFOPLIST_FILE: "Info/SimpleAppTests.plist"
        IPHONEOS_DEPLOYMENT_TARGET: "11.0"
variants:
  $base:
    abstract: true
  SimpleApp: