# https://github.com/lyptt/struct/wiki/Spec-format:-v2.0
version: 2.1.0
configurations:
    Debug:
        type: "debug"
        overrides:
            DEVELOPMENT_TEAM: "ABCXYZ123"
            IPHONEOS_DEPLOYMENT_TARGET: "11.0"
            SWIFT_VERSION: "4.2"
            VERSIONING_SYSTEM: "apple-generic"
            CURRENT_PROJECT_VERSION: "0"
            CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
            CLANG_WARN_COMMA: "YES"
            CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
            CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
            CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
            CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
            CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
            CLANG_WARN_STRICT_PROTOTYPES: "YES"
            SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
        type: "release"
        overrides:
            DEVELOPMENT_TEAM: "ABCXYZ123"
            IPHONEOS_DEPLOYMENT_TARGET: "11.0"
            SWIFT_VERSION: "4.2"
            VERSIONING_SYSTEM: "apple-generic"
            CURRENT_PROJECT_VERSION: "0"
            CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
            CLANG_WARN_COMMA: "YES"
            CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
            CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
            CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
            CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
            CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
            CLANG_WARN_STRICT_PROTOTYPES: "YES"
targets:
    SimpleApp:
        platform: ios
        type: ":application"
        sources:
        - "Sources/SimpleApp"
        configurations:
            Debug:
                SWIFT_VERSION: "$(inherited)"
                IPHONEOS_DEPLOYMENT_TARGET: "11.0"
                PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleApp"
                INFOPLIST_FILE: "Info/SimpleApp.plist"
                SDKROOT: "iphoneos"
                TARGETED_DEVICE_FAMILY: "1"
                MTL_ENABLE_DEBUG_INFO: "YES"
            Release:
                SWIFT_VERSION: "$(inherited)"
                IPHONEOS_DEPLOYMENT_TARGET: "11.0"
                PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleApp"
                INFOPLIST_FILE: "Info/SimpleApp.plist"
                SDKROOT: "iphoneos"
                TARGETED_DEVICE_FAMILY: "1"
    SimpleAppTests:
        platform: ios
        type: ":bundle.unit-test"
        references:
        - "SimpleApp"
        sources:
        - "Sources/SimpleAppTests"
        configurations:
            Debug:
                TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
                SWIFT_VERSION: "$(inherited)"
                LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
                IPHONEOS_DEPLOYMENT_TARGET: "11.0"
                PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleAppTests"
                INFOPLIST_FILE: "Info/SimpleAppTests.plist"
                FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
                TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
                MTL_ENABLE_DEBUG_INFO: "YES"
            Release:
                TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
                SWIFT_VERSION: "$(inherited)"
                LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
                IPHONEOS_DEPLOYMENT_TARGET: "11.0"
                PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleAppTests"
                INFOPLIST_FILE: "Info/SimpleAppTests.plist"
                FRAMEWORK_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)"
                TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SimpleApp.app/SimpleApp"
variants:
    $base:
        abstract: true
    SimpleApp:
