workspace 'SimpleFramework'

target 'SimpleFramework' do

    project 'SimpleFramework'
    platform :ios, '9.0'

    # Comment the next line if you're not using Swift
    # and don't want to use dynamic frameworks
    use_frameworks!

    podspec

end
