# https://github.com/lyptt/struct/wiki/Spec-format:-v2.0

version: 2.1.0
configurations:
  debug:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '9.0'
      SWIFT_VERSION: '4.2'
  release:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '9.0'
      SWIFT_VERSION: '4.2'
targets:
  SimpleFramework:
    platform: ios
    type: ":framework"
    sources:
    - Sources/SimpleFramework
    configurations:
      debug:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleFramework"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        GCC_DYNAMIC_NO_PIC: "NO"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CURRENT_PROJECT_VERSION: "0"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        VERSION_INFO_PREFIX: ""
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        DYLIB_CURRENT_VERSION: "1"
        PRODUCT_NAME: "SCC$(TARGET_NAME:c99extidentifier)"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        DYLIB_COMPATIBILITY_VERSION: "1"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        INSTALL_PATH: "$(LOCAL_LIBRARY_DIR)/Frameworks"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        INFOPLIST_FILE: "Info/SimpleFramework.plist"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        GCC_PREPROCESSOR_DEFINITIONS: "DEBUG1 $(inherited)"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        GCC_OPTIMIZATION_LEVEL: "0"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        SKIP_INSTALL: "YES"
        SWIFT_VERSION: "$(inherited)"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        ONLY_ACTIVE_ARCH: "YES"
        MTL_FAST_MATH: "YES"
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        DEFINES_MODULE: "YES"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        DEBUG_INFORMATION_FORMAT: "dwarf"
        COPY_PHASE_STRIP: "NO"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        CLANG_WARN_COMMA: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: "apple-generic"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        ENABLE_TESTABILITY: "YES"
        SDKROOT: "iphoneos"
        GCC_WARN_UNUSED_VARIABLE: "YES"
      release:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleFramework"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        SWIFT_COMPILATION_MODE: "wholemodule"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CURRENT_PROJECT_VERSION: "0"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        VERSION_INFO_PREFIX: ""
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        DYLIB_CURRENT_VERSION: "1"
        PRODUCT_NAME: "SCC$(TARGET_NAME:c99extidentifier)"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        DYLIB_COMPATIBILITY_VERSION: "1"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        INSTALL_PATH: "$(LOCAL_LIBRARY_DIR)/Frameworks"
        INFOPLIST_FILE: "Info/SimpleFramework.plist"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        SKIP_INSTALL: "YES"
        SWIFT_VERSION: "$(inherited)"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        MTL_FAST_MATH: "YES"
        MTL_ENABLE_DEBUG_INFO: "NO"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        VALIDATE_PRODUCT: "YES"
        DEFINES_MODULE: "YES"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        COPY_PHASE_STRIP: "NO"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        CLANG_WARN_COMMA: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSIONING_SYSTEM: "apple-generic"
        ENABLE_NS_ASSERTIONS: "NO"
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SDKROOT: "iphoneos"
        GCC_WARN_UNUSED_VARIABLE: "YES"
  SimpleFrameworkTests:
    platform: ios
    type: ":bundle.unit-test"
    references:
    - location: SimpleFramework
    sources:
    - Sources/SimpleFrameworkTests
    configurations:
      debug:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleFrameworkTests"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        GCC_DYNAMIC_NO_PIC: "NO"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CURRENT_PROJECT_VERSION: "0"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        PRODUCT_NAME: "$(TARGET_NAME)"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        INFOPLIST_FILE: "Info/SimpleFrameworkTests.plist"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        GCC_PREPROCESSOR_DEFINITIONS: "DEBUG1 $(inherited)"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        GCC_OPTIMIZATION_LEVEL: "0"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        SWIFT_VERSION: "$(inherited)"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        ONLY_ACTIVE_ARCH: "YES"
        MTL_FAST_MATH: "YES"
        MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        DEBUG_INFORMATION_FORMAT: "dwarf"
        COPY_PHASE_STRIP: "NO"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        CLANG_WARN_COMMA: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        ENABLE_TESTABILITY: "YES"
        SDKROOT: "iphoneos"
        GCC_WARN_UNUSED_VARIABLE: "YES"
      release:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        GCC_WARN_UNUSED_FUNCTION: "YES"
        CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
        CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: "com.SomeCoolCompany.SimpleFrameworkTests"
        CLANG_WARN_STRICT_PROTOTYPES: "YES"
        ALWAYS_SEARCH_USER_PATHS: "NO"
        SWIFT_COMPILATION_MODE: "wholemodule"
        CLANG_WARN_INFINITE_RECURSION: "YES"
        CURRENT_PROJECT_VERSION: "0"
        CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
        IPHONEOS_DEPLOYMENT_TARGET: "9.0"
        CLANG_WARN_UNREACHABLE_CODE: "YES"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        PRODUCT_NAME: "$(TARGET_NAME)"
        GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
        ENABLE_STRICT_OBJC_MSGSEND: "YES"
        INFOPLIST_FILE: "Info/SimpleFrameworkTests.plist"
        CLANG_ENABLE_OBJC_WEAK: "YES"
        CLANG_WARN_EMPTY_BODY: "YES"
        GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
        CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
        CLANG_WARN_BOOL_CONVERSION: "YES"
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
        CLANG_WARN_SUSPICIOUS_MOVE: "YES"
        SWIFT_VERSION: "$(inherited)"
        CLANG_WARN_CONSTANT_CONVERSION: "YES"
        CLANG_WARN_ENUM_CONVERSION: "YES"
        CODE_SIGN_STYLE: "Automatic"
        GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
        MTL_FAST_MATH: "YES"
        MTL_ENABLE_DEBUG_INFO: "NO"
        GCC_WARN_UNDECLARED_SELECTOR: "YES"
        CLANG_ANALYZER_NONNULL: "YES"
        GCC_C_LANGUAGE_STANDARD: "gnu11"
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
        CLANG_CXX_LIBRARY: "libc++"
        CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
        CLANG_WARN_INT_CONVERSION: "YES"
        CLANG_ENABLE_MODULES: "YES"
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
        VALIDATE_PRODUCT: "YES"
        CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
        CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        COPY_PHASE_STRIP: "NO"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
        CLANG_WARN_COMMA: "YES"
        CLANG_ENABLE_OBJC_ARC: "YES"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_NS_ASSERTIONS: "NO"
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        SDKROOT: "iphoneos"
        GCC_WARN_UNUSED_VARIABLE: "YES"
variants:
  $base:
    abstract: true
  SimpleFramework: