# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '1.100.0'

default_platform :ios

#===

platform :ios do

  lane :beforeRelease do

    ensure_git_branch(
      branch: 'release/*'
    )

    # ===

    ensure_git_status_clean

    # ===

    pod_lib_lint(
      allow_warnings: true,
      quick: true
    )

    # ===

    versionNumber = get_version_number(xcodeproj: 'RepoConfigurator.xcodeproj')
    puts 'Current VERSION number: ' + versionNumber

    # === Infer new version number

    defaultNewVersion = git_branch.split('/').last

    # === Define new version number

    useInferredNEWVersionNumber = prompt(
      text: 'Proceed with inferred NEW version number (' + defaultNewVersion + ')?',
      boolean: true
    )

    if useInferredNEWVersionNumber

      newVersionNumber = defaultNewVersion

    else

      newVersionNumber = prompt(text: 'New VERSION number:')

    end

    # === Apply NEW version number and increment build number

    increment_version_number(
      xcodeproj: 'RepoConfigurator.xcodeproj',
      version_number: newVersionNumber
    )

    increment_build_number(
      xcodeproj: 'RepoConfigurator.xcodeproj'
    )

    # ===

    newBuildNumber = get_build_number(xcodeproj: 'RepoConfigurator.xcodeproj')

    commit_version_bump( # it will fail if more than version bump
      xcodeproj: 'RepoConfigurator.xcodeproj',
      message: 'Version Bump to ' + newVersionNumber + ' (' + newBuildNumber + ')'
    )

    # ===

    version_bump_podspec(
      path: './XCERepoConfigurator.podspec',
      version_number: newVersionNumber
    )

    git_commit(
      path: './XCERepoConfigurator.podspec',
      message: 'Version Bump to ' + newVersionNumber + ' in Podspec file'
    )

  end

end
